language: scala
scala:
- 2.12.3
jdk:
- oraclejdk8
before_cache:
- du -h -d 1 $HOME/.ivy2/
- du -h -d 2 $HOME/.sbt/
- du -h -d 4 $HOME/.coursier/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
  - $HOME/.sbt/cache
  - $HOME/.sbt/0.13
  - $HOME/.sbt/boot/
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.ivy2
before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_398281636a6f_key -iv $encrypted_398281636a6f_iv -in secring.gpg.enc -out secring.gpg -d;
  fi
- export PATH=${PATH}:./vendor/bundle
script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI
after_success:
- bash <(curl -s https://codecov.io/bash)
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    if grep -q "SNAPSHOT" version.sbt; then
      sbt ++$TRAVIS_SCALA_VERSION publish;
    else
      sbt ++$TRAVIS_SCALA_VERSION orgUpdateDocFiles;
      git reset --hard HEAD;
      git clean -f;
      git checkout master;
      git pull origin master;
      sbt ++$TRAVIS_SCALA_VERSION release;
    fi
  fi
